---
# Al agregar nuevos objetos, no repetir ids. 
# Para facilitar el conteo de ids, ordenar la descripcion 
# de cada objeto, por su id de menor a mayor.

# Atencion los valores modulizadores de color RGB van de 1 a 255
# (No poner 0, en cuyo caso, el programara levantara error.)

player_number: 1
sections: 
    [
        background,
        blocks_metal, 
        blocks_rock, 
        blocks_acid, 
        rocks_one, 
        rocks_two, 
        rocks_three, 
        rocks_four, 
        rocks_five, 
        rocks_six, 
        rocks_seven, 
        rocks_eight,
        doors_one, 
        buttons, 
        triangles_botom_left,
        triangles_botom_right,
        triangles_top_left,
        triangles_top_right,
        barriers,
        energy_balls_green, 
        receivers,
        emitters_right,
        cakes, 
        portals_blue, 
        portals_orange, 
        chells,
        pin_tools,
        loadings,
        records
    ]
blocks_metal:
    width: 1
    height: 1
    id_coordinates:
    # Distanciar ids de a 1.
        [      
            # Limites del mapa
            # Pared izquierda
            {id: 0, xCoord: -7.5, yCoord: 0.5},
            {id: 1, xCoord: -7.5, yCoord: 1.5},
            {id: 2, xCoord: -7.5, yCoord: 2.5},
            {id: 3, xCoord: -7.5, yCoord: 3.5},
            {id: 4, xCoord: -7.5, yCoord: 4.5},
            {id: 5, xCoord: -7.5, yCoord: 5.5},
            {id: 6, xCoord: -7.5, yCoord: 6.5},
            {id: 7, xCoord: -7.5, yCoord: 7.5},
            {id: 8, xCoord: -7.5, yCoord: 8.5},
            {id: 9, xCoord: -7.5, yCoord: 9.5},
            {id: 10, xCoord: -7.5, yCoord: 10.5},
            {id: 11, xCoord: -7.5, yCoord: 11.5},
            {id: 12, xCoord: -7.5, yCoord: 12.5},
            {id: 13, xCoord: -7.5, yCoord: 13.5},
            {id: 14, xCoord: -7.5, yCoord: 14.5},
            {id: 15, xCoord: -7.5, yCoord: 15.5},
            # Techo
            {id: 16, xCoord: -6.5, yCoord: 20.5},
            {id: 17, xCoord: -5.5, yCoord: 20.5},
            {id: 18, xCoord: -4.5, yCoord: 20.5},
            {id: 19, xCoord: -3.5, yCoord: 20.5},
            {id: 20, xCoord: -2.5, yCoord: 20.5},
            {id: 21, xCoord: -1.5, yCoord: 20.5},
            {id: 22, xCoord: -0.5, yCoord: 20.5},
            {id: 23, xCoord: 0.5, yCoord: 20.5},
            {id: 24, xCoord: 1.5, yCoord: 20.5},
            {id: 25, xCoord: 2.5, yCoord: 20.5},
            {id: 26, xCoord: 3.5, yCoord: 20.5},
            {id: 27, xCoord: 4.5, yCoord: 20.5},
            {id: 28, xCoord: 5.5, yCoord: 20.5},
            {id: 29, xCoord: 6.5, yCoord: 20.5},
            # Pared derecha
            {id: 30, xCoord: 7.5, yCoord: 15.5},
            {id: 31, xCoord: 7.5, yCoord: 14.5},
            {id: 32, xCoord: 7.5, yCoord: 13.5},
            {id: 33, xCoord: 7.5, yCoord: 12.5},
            {id: 34, xCoord: 7.5, yCoord: 11.5},
            {id: 35, xCoord: 7.5, yCoord: 10.5},
            {id: 36, xCoord: 7.5, yCoord: 9.5},
            {id: 37, xCoord: 7.5, yCoord: 8.5},
            {id: 38, xCoord: 7.5, yCoord: 7.5},
            {id: 39, xCoord: 7.5, yCoord: 6.5},
            {id: 40, xCoord: 7.5, yCoord: 5.5},
            {id: 41, xCoord: 7.5, yCoord: 4.5},
            {id: 42, xCoord: 7.5, yCoord: 3.5},
            {id: 43, xCoord: 7.5, yCoord: 2.5},
            {id: 44, xCoord: 7.5, yCoord: 1.5},
            {id: 45, xCoord: 7.5, yCoord: 0.5},
            # Piso 0
            {id: 46, xCoord: 6.5, yCoord: 0.5},
            {id: 47, xCoord: 5.5, yCoord: 0.5},
            {id: 48, xCoord: 4.5, yCoord: 0.5},
            {id: 49, xCoord: 3.5, yCoord: 0.5},
            {id: 50, xCoord: 2.5, yCoord: 0.5},
            {id: 51, xCoord: 1.5, yCoord: 0.5},
            {id: 52, xCoord: 0.5, yCoord: 0.5},
            {id: 53, xCoord: -0.5, yCoord: 0.5},
            {id: 54, xCoord: -1.5, yCoord: 0.5},
            {id: 55, xCoord: -2.5, yCoord: 0.5},
            {id: 56, xCoord: -3.5, yCoord: 0.5},
            {id: 57, xCoord: -4.5, yCoord: 0.5},
            {id: 58, xCoord: -5.5, yCoord: 0.5},
            {id: 59, xCoord: -6.5, yCoord: 0.5},
            # Piso 1
            #{id: 60, xCoord: 6.5, yCoord: 5.5},
            #{id: 61, xCoord: 5.5, yCoord: 5.5},
            #{id: 62, xCoord: 4.5, yCoord: 5.5},
            #{id: 63, xCoord: 3.5, yCoord: 5.5},
            {id: 64, xCoord: 2.5, yCoord: 5.5},
            {id: 65, xCoord: 1.5, yCoord: 5.5},
            {id: 66, xCoord: 0.5, yCoord: 5.5},
            {id: 67, xCoord: -0.5, yCoord: 5.5},
            {id: 68, xCoord: -1.5, yCoord: 5.5},
            {id: 69, xCoord: -2.5, yCoord: 5.5},
            {id: 70, xCoord: -3.5, yCoord: 5.5},
            {id: 71, xCoord: -4.5, yCoord: 5.5},
            {id: 72, xCoord: -5.5, yCoord: 5.5},
            {id: 73, xCoord: -6.5, yCoord: 5.5},
            # Piso 2
            {id: 74, xCoord: 6.5, yCoord: 10.5},
            {id: 75, xCoord: 5.5, yCoord: 10.5},
            {id: 76, xCoord: 4.5, yCoord: 10.5},
            {id: 77, xCoord: 3.5, yCoord: 10.5},
            {id: 78, xCoord: 2.5, yCoord: 10.5},
            {id: 79, xCoord: 1.5, yCoord: 10.5},
            {id: 80, xCoord: 0.5, yCoord: 10.5},
            {id: 81, xCoord: -0.5, yCoord: 10.5},
            {id: 82, xCoord: -1.5, yCoord: 10.5},
            {id: 83, xCoord: -2.5, yCoord: 10.5},
            #{id: 84, xCoord: -3.5, yCoord: 10.5},
            #{id: 85, xCoord: -4.5, yCoord: 10.5},
            #{id: 86, xCoord: -5.5, yCoord: 10.5},
            #{id: 87, xCoord: -6.5, yCoord: 10.5},
            # Piso 3
            #{id: 88, xCoord: 6.5, yCoord: 15.5},
            #{id: 89, xCoord: 5.5, yCoord: 15.5},
            #{id: 90, xCoord: 4.5, yCoord: 15.5},
            #{id: 91, xCoord: 3.5, yCoord: 15.5},
            {id: 92, xCoord: 2.5, yCoord: 15.5},
            {id: 93, xCoord: 1.5, yCoord: 15.5},
            {id: 94, xCoord: 0.5, yCoord: 15.5},
            {id: 95, xCoord: -0.5, yCoord: 15.5},
            {id: 96, xCoord: -1.5, yCoord: 15.5},
            {id: 97, xCoord: -2.5, yCoord: 15.5},
            {id: 98, xCoord: -3.5, yCoord: 15.5},
            {id: 99, xCoord: -4.5, yCoord: 15.5},
            {id: 100, xCoord: -5.5, yCoord: 15.5},
            {id: 101, xCoord: -6.5, yCoord: 15.5}
        ]
blocks_acid:
    width: 1
    height: 1
    id_coordinates:
        []
blocks_rock:
    width: 1
    height: 1
    id_coordinates:
        [
            {id: 102, xCoord: -7.5, yCoord: 16.5},
            {id: 103, xCoord: -7.5, yCoord: 17.5},
            {id: 104, xCoord: -7.5, yCoord: 18.5},
            {id: 105, xCoord: -7.5, yCoord: 19.5},
            {id: 106, xCoord: -7.5, yCoord: 20.5},
            {id: 107, xCoord: 7.5, yCoord: 16.5},
            {id: 108, xCoord: 7.5, yCoord: 17.5},
            {id: 109, xCoord: 7.5, yCoord: 18.5},
            {id: 110, xCoord: 7.5, yCoord: 19.5},
            {id: 111, xCoord: 7.5, yCoord: 20.5},
        ]
doors_one:
    width: 1.0
    height: 2.0
    id_coordinates:
       - id: 112
         number: 1
         xCoord: 0.5
         yCoord: 2.0
         conditions:
             - [{cond_id: 116,  condition: true}]
             - [{cond_id: 117,  condition: true}]
       - id: 113
         number: 1
         xCoord: -3.5
         yCoord: 17.0
         conditions:
             - [{cond_id: 116,  condition: true}, {cond_id: 117,  condition: true}]
buttons:
    width: 2
    height: 0.5
    id_coordinates:
        [
            {id: 116, xCoord: -3.0, yCoord: 1.25, door_ids: [112]},
            {id: 117, xCoord: 6.0, yCoord: 1.25, door_ids: [112]}
        ]
chells:
    width: 1
    height: 1.5
    id_coordinates: 
        [
             {id: 120, xCoord: -5.5, yCoord: 1.75, redMod: 255, greenMod: 1, blueMod: 1}
             #{id: 103, xCoord: 1, yCoord: 1.75, redMod: 1, greenMod: 1, blueMod: 255},
             #{id: 104, xCoord: -1, yCoord: 1.75, redMod: 1, greenMod: 255, blueMod: 1}
        ]
portals_blue:
    width: 1.5
    height: 1.5
    id_coordinates: 
        [
            {id: 121, xCoord: 1000, yCoord: 1000},
            #{id: 106, xCoord: 2000, yCoord: 2000},
            #{id: 107, xCoord: 3000, yCoord: 3000}
        ]
portals_orange:
    width: 1.5
    height: 1.5
    id_coordinates: 
        [
            {id: 122, xCoord: 4000, yCoord: 4000},
            #{id: 109, xCoord: 5000, yCoord: 5000},
            #{id: 110, xCoord: 6000, yCoord: 6000}
        ]
pin_tools:
    width: 1
    height: 1
    id_coordinates:
        # Recomendacion: Usar los mismo colores de las Chells que son propietarios de cada pin tool
        [
            {id: 123, xCoord: 1000, yCoord: 1000, redMod: 255, greenMod: 1, blueMod: 1, chell_id: 102},
            #{id: 112, xCoord: 2000, yCoord: 2000, redMod: 1, greenMod: 1, blueMod: 255, chell_id: 103},
            #{id: 113, xCoord: 2000, yCoord: 2000, redMod: 1, greenMod: 255, blueMod: 1, chell_id: 104}
        ]

energy_balls_green:
    width: 0.5
    height: 0.5
    id_coordinates:
        []

rocks_one:
    width: 1.0
    height: 1.0
    id_coordinates:
        [
            {id: 140, xCoord: 0.5, yCoord: 6.5},
        ]
rocks_two:
    width: 1.0
    height: 1.0
    id_coordinates:
        []
rocks_three:
    width: 1.0
    height: 1.0
    id_coordinates:
        []
rocks_four:
    width: 1.0
    height: 1.0
    id_coordinates:
        []
rocks_five:
    width: 1.0
    height: 1.0
    id_coordinates:
        []
rocks_six:
    width: 1.0
    height: 1.0
    id_coordinates:
        []
rocks_seven:
    width: 1.0
    height: 1.0
    id_coordinates:
        []
rocks_eight:
    width: 1.0
    height: 1.0
    id_coordinates:
        []
barriers:
    [
        {id: 150, xCoord: -1, yCoord: 8, width: 0.25, height: 5},
    ]
triangles_botom_left:
    width: 1
    height: 1
    id_coordinates:
        []
triangles_botom_right:
    width: 1
    height: 1
    id_coordinates:
        []
triangles_top_left:
    width: 1
    height: 1
    id_coordinates:
        []
triangles_top_right:
    width: 1
    height: 1
    id_coordinates:
        []
receivers:
    width: 1
    height: 1
    id_coordinates:
        []
emitters_right:
    width: 1
    height: 1
    id_coordinates:
        []
emitters_left:
    width: 1
    height: 1
    id_coordinates:
        []
emitters_up:
    width: 1
    height: 1
    id_coordinates:
        []
emitters_down:
    width: 1
    height: 1
    id_coordinates:
        []
cakes:
    width: 1
    height: 1
    id_coordinates:
        []
background:
    width: 100
    height: 50
    id_coordinates:
        [
            {id: 1000, xCoord: 0, yCoord: 0}
        ]
records:
    width: 1
    height: 1
    id_coordinates:
        [
            {id: 1001, xCoord: 0, yCoord: 0}
        ]
loadings:
    # De esta seccion solo importa el id.
    width: 1
    height: 1
    id_coordinates:
        [
            {id: 1002, xCoord: 0, yCoord: 0}
        ]