server:
    default_port: "8082"
    request_executors: 5
game_loop:
    wait_before_start_seconds: 2
    step_max_time_microseconds: 10000
simulation:
    time_step_seconds: 0.015
    velocity_iterations: 8
    position_iterations: 2
game_options:
    gravity_x: 0.0
    gravity_y: -9.807
    chell:
        move_speed: 3.0
        jump_speed: 6.0
        jump_timeout_milliseconds: 100
    energy_ball:
        speed: 2.0
        reset_time_milliseconds: 15000
    pin_tool:
        reset_time_milliseconds: 10000
available_maps:
    - map_0.yaml
    - map_1.yaml
    - map_2.yaml
    - map_3.yaml
    - map_4.yaml
    - map_5.yaml
